routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

route::get('/prueba', 'PruebaController@index');
route::get('/inicio',function (){
   return view('inicio');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/book','BookController');

Route::resource('/user','UserController');
Route::get('/excel','ExcelController@exportar');
//Route::get('/export-users', 'ExcelController@exportUsers');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = [
        'name', 'description', 'author_id' , 'house_id',
    ];

    public function author() {
        $this->belongsTo(Author::class);
    }

    public function house() {
        $this->belongsTo(house::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Book;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Excel;


class bookController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // otro metodo para obtener datos ->$datos = DB::table('users')->get();
        // por medio de eloquent utilizando el metodo all() se recuperan todos los registros

        $datos = Book::all();

        return view('book.index',compact('datos')); // con compact paso los datos de los libros
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //


        $this->validate($request,
            ['name'=>'required|min:3|string|max:30|unique:books,name',
                'description'=>'required|string|min:5|max:30|',
                'author_id'=>'required|Numeric',
                'house_id'=>'required|Numeric'
            ],

            [   'name.required'=>'El nombre es obligatorio',
                'description.required'=>'La descripcion es obligatoria',
                'author_id.required' => 'eliga un autor ',
                'house_id.required' => 'eliga una editorial',

                'name.min'=>'el nombre debe tener mas de 3 caracteres',
                'description.min'=>'La descripcion debe tener mas de 5 caracteres',
                'author_id.Numeric' => 'el campo debe ser de tipo numerico',
                'house_id.Numeric' => 'el campo debe ser de tipo numerico',

                'name.max'=>'ha excedido el numero maximo de caracteres',
                'description.max'=>'ha excedido el numero maximo de caracteres',

                'name.unique'=>'El libro ya se encuentra registrado en la base de datos',

            ]);

        $data = $request->all();
        //dd($data);
        Book::create([
            'name' => $data['name'],
            'description' => $data['description'],
            'author_id' => $data['author_id'],
            'house_id' => $data['house_id'],
        ]);

        return redirect()->route('book.index');
        //return url('/book');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)

    {
        //$datos = Book::find($id);
        //$datos = Book::where("id","=",$id)->find(1);


            $datos = Book::findOrFail($id);

            /*
        if ($datos == null) {
            //return view('errors.404');

            return response()->view('errors.404', [], 404);
        }
        */
        //dd($datos);
        return view('book.show',compact('datos') );


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $book = Book::findOrFail($id);
        //dd($book);
        return view('book.edit',compact('book'));
        //return "procesando";
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        //
/*
        $this->validate($request,
            ['name'=>'required|min:3|string|max:30|unique:books,name',
                'description'=>'required|string|min:5|max:30|',
                'author_id'=>'required|Numeric',
                'house_id'=>'required|Numeric'
            ],

            [   'name.required'=>'El nombre es obligatorio',
                'description.required'=>'La descripcion es obligatoria',
                'author_id.required' => 'eliga un autor ',
                'house_id.required' => 'eliga una editorial',

                'name.min'=>'el nombre debe tener mas de 3 caracteres',
                'description.min'=>'La descripcion debe tener mas de 5 caracteres',
                'author_id.Numeric' => 'el campo debe ser de tipo numerico',
                'house_id.Numeric' => 'el campo debe ser de tipo numerico',

                'name.max'=>'ha excedido el numero maximo de caracteres',
                'description.max'=>'ha excedido el numero maximo de caracteres',

                'name.unique'=>'El libro ya se encuentra registrado en la base de datos',

            ]);

        */
$data = $request->all();



        $post = Book::findOrFail($id);
        //echo $post->name;
        //echo $request->name;
        //dd($data);

        $post->name = $request->name;
        $post->description = $request->description;
        $post->author_id = $request->author_id;
        $post->house_id = $request->house_id;

        $post->save();
        //Book::updated($data);

        /*
        Book::create([
            'name' => $data['name'],
            'description' => $data['description'],
            'author_id' => $data['author_id'],
            'house_id' => $data['house_id'],
        ]);*/

        return redirect()->route('book.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();
        return redirect()->route('book.index');
    }

    public function ExportarExcel() {

    }
}

resources/views/book/create.blade.php
@extends('layouts.principal')
@section('content')

  <h1>Creación de usuarios</h1>

  @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @php
                $valores =0
              @endphp
              @foreach ($errors->all() as $error)

                          @php
                              $valores +=1
                          @endphp

              @endforeach
          </ul>
          <ul> Existen {{$valores}} errores en el formulario </ul>
      </div>
  @endif

  <form method="post" action="{{ route('book.store') }}" >

      {{ csrf_field() }}
      <div class="form-group">
          <label for="name">Titulo del libro</label>
          <input type="text" class="form-control" id="name" name="name" placeholder="Agregué el titulo del libro" value="{{old('name')}}" >
          <small class="text-danger">{{ $errors->first('name') }} </small>
      </div>
      <div class="form-group">
          <label for="description">Descripción</label>
          <input type="text" class="form-control" id="description" name="description" placeholder="agregue una descripción" value="{{old('description')}}">
      </div>

      <div class="form-group">
          <label for="author_id">Autor</label>
          <input type="number" class="form-control" id="author_id" name="author_id"  placeholder="agregue el autor" value="{{old('author_id')}}"  >

      </div>
      <div class="form-group">
          <label for="house_id">Editorial</label>
          <input type="number" class="form-control" id="house_id" name="house_id" placeholder="agregue la editorial" value="{{old('house_id')}}">
      </div>

      <button type="submit" class="btn btn-primary">Enviar</button>
  </form>


@endsection

resources/views/book/edit.blade.php
@extends('layouts.principal')
@section('content')

    <h1>Editar usuarios</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @php
                    $valores =0
                @endphp
                @foreach ($errors->all() as $error)

                    @php
                        $valores +=1
                    @endphp

                @endforeach
            </ul>
            <ul> Existen {{$valores}} errores en el formulario </ul>
        </div>
    @endif

    <form method="post" action="{{ url("book/$book->id") }}" >

        {{ csrf_field() }}
        {{method_field('PUT')}}

        <div class="form-group">
            <label for="name">Titulo del libro</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Agregué el titulo del libro" value="{{$book->name}}" >
            <small class="text-danger">{{ $errors->first('name') }} </small>
        </div>
        <div class="form-group">
            <label for="description">Descripción</label>
            <input type="text" class="form-control" id="description" name="description" placeholder="agregue una descripción" value="{{$book->description}}">
        </div>

        <div class="form-group">
            <label for="author_id">Autor</label>
            <input type="number" class="form-control" id="author_id" name="author_id"  placeholder="agregue el autor" value="{{$book->author_id}}">

        </div>
        <div class="form-group">
            <label for="house_id">Editorial</label>
            <input type="number" class="form-control" id="house_id" name="house_id" placeholder="agregue la editorial" value="{{$book->house_id}}">
        </div>

        <button type="submit" class="btn btn-primary">Actualizar usuarios</button>
    </form>


@endsection

resources/views/book/index.blade.php
@extends('layouts.principal')
    @section('content')

        @forelse($datos as $libros)
            <li>{{ $libros->name }}  ,
                <a href="{{ route('book.show',['id' => $libros->id]) }}"> detalles </a> |
                <a href="{{ route('book.edit',['id' => $libros->id]) }}"> Editar </a> |

                <form method="post" action=" {{route('book.destroy',$libros)}}" >
                    {{ csrf_field() }}
                    {{method_field('DELETE')}}
                    <button type="submit" class="btn btn-link">Eliminar</button>
                </form>

            </li>

        @empty
            <li>No hay libros aun.</li>
        @endforelse
    @endsection

resources/views/book/show.blade.php
@extends('layouts.principal')
@section('content')

    <p> Nombre del libro: {{ $datos->name}} </p>

@endsection